# gradle properties
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=1G
org.gradle.parallel=false
org.gradle.configuration-cache=false
org.gradle.caching=true

# mod properties
mod_id=mapdrawclient
mod_name=MapDraw Client
mod_version=0.0.1-alpha
mod_archives_base_name=mapdrawclient
mod_maven_group=top.colorgarden.mapdrawclient
mod_description=MapDraw 插件的 Fabric 客户端扩展：原生画板 GUI 与 mapdraw:main 通道全部端口
mod_license=MIT
mod_homepage=https://github.com/colorgarden/MapDrawClient
mod_sources=https://github.com/colorgarden/MapDrawClient

# loader / loom
loader_version=0.19.5
loom_version=1.18-SNAPSHOT